import { useMemo, useState } from "react";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { applicationBuilderApi, type ApplicationProject, type CapabilityCatalog, type PlatformAdvisorRequest } from "../../api/applicationBuilder";
import { useToasts } from "../../stores";

const platformOptions = ["web", "linux", "windows", "macos", "android", "ios"] as const;
const featureOptions: Array<{ key: keyof PlatformAdvisorRequest; label: string }> = [
  { key: "offline", label: "Offline" }, { key: "localFiles", label: "Local files" },
  { key: "tray", label: "Tray" }, { key: "background", label: "Background" },
  { key: "gpu", label: "GPU" }, { key: "embeddedServer", label: "Embedded server" },
  { key: "store", label: "Store" }, { key: "preferNativeFeel", label: "Native feel" },
  { key: "preferWebReuse", label: "Web reuse" }, { key: "preferSmallSize", label: "Small package" },
];

export function PlatformAdvisorPanel({ project, capabilities }: { project: ApplicationProject; capabilities?: CapabilityCatalog }) {
  const qc = useQueryClient(); const show = useToasts((state) => state.show);
  const savedPlatforms = Array.from(new Set((Array.isArray(project.spec.targets) ? project.spec.targets : []).flatMap((target) => target && typeof target === "object" && Array.isArray((target as Record<string, unknown>).platforms) ? (target as Record<string, unknown>).platforms as string[] : []))).filter((item): item is PlatformAdvisorRequest["platforms"][number] => platformOptions.includes(item as PlatformAdvisorRequest["platforms"][number]));
  const [preferences, setPreferences] = useState<PlatformAdvisorRequest>({
    platforms: savedPlatforms.length ? savedPlatforms : ["web"], offline: false, localFiles: false, tray: false,
    background: false, gpu: false, embeddedServer: false, store: false, preferredLanguage: "any",
    preferNativeFeel: false, preferWebReuse: true, preferSmallSize: false,
  });
  const [selected, setSelected] = useState<Set<string>>(new Set());
  const advisor = useMutation({ mutationFn: () => applicationBuilderApi.advisePlatforms(preferences), onSuccess: (result) => setSelected(new Set([result.recommendedId])) });
  const recommendations = advisor.data?.recommendations ?? [];
  const selectedRecommendations = recommendations.filter((item) => selected.has(item.frameworkId));
  const coverage = new Set(selectedRecommendations.flatMap((item) => preferences.platforms.filter((platform) => item.platforms.includes(platform))));
  const missingCoverage = preferences.platforms.filter((item) => !coverage.has(item));
  const proposedTargets = selectedRecommendations.map((item) => ({ id: item.frameworkId, framework: item.frameworkId, platforms: preferences.platforms.filter((platform) => item.platforms.includes(platform)) })).filter((item) => item.platforms.length);
  const proposedSpec = useMemo(() => ({ ...project.spec, targets: proposedTargets }), [project.spec, JSON.stringify(proposedTargets)]);
  const save = useMutation({
    mutationFn: () => applicationBuilderApi.update(project.id, { spec: proposedSpec }),
    onSuccess: async () => { show("Platform targetを保存しました"); await qc.invalidateQueries({ queryKey: ["application-project", project.id] }); },
    onError: (reason) => show(reason instanceof Error ? reason.message : "Targetを保存できませんでした", "error"),
  });
  const preflight = useMutation({ mutationFn: () => applicationBuilderApi.preflight(project, proposedSpec) });
  const togglePlatform = (platform: PlatformAdvisorRequest["platforms"][number]) => setPreferences((current) => ({ ...current, platforms: current.platforms.includes(platform) ? current.platforms.filter((item) => item !== platform) : [...current.platforms, platform] }));
  const toggleFramework = (frameworkId: string) => setSelected((current) => { const next = new Set(current); if (next.has(frameworkId)) next.delete(frameworkId); else next.add(frameworkId); return next; });
  const canUseTargets = selectedRecommendations.length > 0 && missingCoverage.length === 0;

  return <section aria-label="Platform Advisor" className="rounded-2xl border border-zinc-200 bg-white p-4 dark:border-zinc-800 dark:bg-zinc-900"><div className="mb-3 flex items-start gap-3"><div className="min-w-0 flex-1"><h2 className="text-sm font-semibold">Platform Advisor · B1</h2><p className="mt-1 text-xs leading-relaxed text-zinc-500">固定registryから推薦し、複数target／overrideを保存前にpreflightします。生成やbuildは実行しません。</p></div><span className="rounded-full bg-blue-50 px-2 py-1 text-[10px] font-semibold text-blue-700 dark:bg-blue-950/30 dark:text-blue-300">Read-only preflight</span></div>
    <fieldset aria-label="Target platforms"><legend className="mb-1 text-[10px] text-zinc-400">Platforms</legend><div className="grid grid-cols-3 gap-1 sm:grid-cols-6">{platformOptions.map((platform) => <label key={platform} className="flex min-h-11 items-center gap-2 rounded-lg bg-zinc-50 px-2 text-[10px] capitalize dark:bg-zinc-950"><input aria-label={`Target platform ${platform}`} type="checkbox" checked={preferences.platforms.includes(platform)} disabled={preferences.platforms.length === 1 && preferences.platforms.includes(platform)} onChange={() => togglePlatform(platform)} className="h-4 w-4" />{platform}</label>)}</div></fieldset>
    <details className="mt-2"><summary className="min-h-11 cursor-pointer py-3 text-xs font-medium">Requirements and preferences</summary><div className="grid grid-cols-2 gap-1 sm:grid-cols-3">{featureOptions.map(({ key, label }) => <label key={key} className="flex min-h-11 items-center gap-2 rounded-lg bg-zinc-50 px-2 text-[10px] dark:bg-zinc-950"><input aria-label={`Requirement ${label}`} type="checkbox" checked={Boolean(preferences[key])} onChange={(event) => setPreferences((current) => ({ ...current, [key]: event.target.checked }))} className="h-4 w-4" />{label}</label>)}</div><label className="mt-2 block text-[10px] text-zinc-400">Preferred language<select aria-label="Preferred language" value={preferences.preferredLanguage} onChange={(event) => setPreferences((current) => ({ ...current, preferredLanguage: event.target.value as PlatformAdvisorRequest["preferredLanguage"] }))} className="mt-1 min-h-11 w-full rounded-lg border border-zinc-300 bg-transparent px-3 text-xs dark:border-zinc-700"><option value="any">Any</option>{["csharp", "typescript", "rust", "dart", "kotlin", "cpp"].map((item) => <option key={item} value={item}>{item}</option>)}</select></label></details>
    <button type="button" onClick={() => advisor.mutate()} disabled={advisor.isPending} className="mt-3 min-h-11 w-full rounded-xl bg-blue-600 text-xs font-semibold text-white disabled:opacity-40">{advisor.isPending ? "Scoring…" : "Recommend platforms"}</button>
    {advisor.error && <p role="alert" className="mt-2 rounded-lg bg-red-50 p-2 text-xs text-red-600">{advisor.error instanceof Error ? advisor.error.message : "推薦できませんでした"}</p>}
    {advisor.data && <section aria-label="Platform recommendations" className="mt-4 space-y-2"><div className="flex items-center justify-between"><h3 className="text-xs font-semibold">Ranked recommendations</h3><span className="text-[10px] text-zinc-400">Top: {advisor.data.recommendedId}</span></div>{recommendations.map((item, index) => { const compatible = preferences.platforms.some((platform) => item.platforms.includes(platform)); return <article key={item.frameworkId} className={`rounded-xl border p-3 ${selected.has(item.frameworkId) ? "border-blue-400 bg-blue-50/50 dark:bg-blue-950/20" : "border-zinc-200 dark:border-zinc-700"}`}><div className="flex items-start gap-2"><label className="flex min-h-11 min-w-0 flex-1 items-center gap-2"><input aria-label={`Select ${item.label}`} type="checkbox" checked={selected.has(item.frameworkId)} disabled={!compatible} onChange={() => toggleFramework(item.frameworkId)} className="h-5 w-5 shrink-0" /><span className="min-w-0"><strong className="block text-xs">#{index + 1} {item.label}</strong><span className="text-[10px] text-zinc-400">{item.language} · score {item.score} · {item.status}</span></span></label><span className={`rounded-full px-2 py-1 text-[9px] ${item.matrix.source === "available" ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700 dark:bg-amber-950/30"}`}>source {item.matrix.source}</span></div><p className="mt-1 text-[10px] leading-relaxed text-zinc-500">{item.reasons.slice(0, 2).join(" · ") || "適合理由なし"}</p>{item.constraints.length > 0 && <p className="mt-1 text-[10px] leading-relaxed text-amber-700 dark:text-amber-300">制約: {item.constraints.slice(0, 3).join(" · ")}</p>}</article>; })}</section>}
    {selectedRecommendations.length > 0 && <div className="mt-3 space-y-2">{missingCoverage.length > 0 && <p role="alert" className="rounded-lg bg-amber-50 p-2 text-xs text-amber-700 dark:bg-amber-950/30">未カバーplatform: {missingCoverage.join(", ")}</p>}<div className="grid gap-2 sm:grid-cols-2"><button type="button" onClick={() => preflight.mutate()} disabled={!canUseTargets || preflight.isPending} className="min-h-11 rounded-xl border border-zinc-300 text-xs font-semibold disabled:opacity-40 dark:border-zinc-700">{preflight.isPending ? "Checking…" : "Preflight selected targets"}</button><button type="button" onClick={() => save.mutate()} disabled={!canUseTargets || save.isPending} className="min-h-11 rounded-xl bg-accent-600 text-xs font-semibold text-white disabled:opacity-40">Apply selected targets</button></div></div>}
    {preflight.data && <section aria-label="Platform preflight" className="mt-4 space-y-2"><div className={`rounded-xl p-3 text-xs font-semibold ${preflight.data.readyForGeneration ? "bg-emerald-50 text-emerald-700" : "bg-amber-50 text-amber-700 dark:bg-amber-950/30 dark:text-amber-300"}`}>Generation: {preflight.data.readyForGeneration ? "ready" : "blocked"} · Local build: {preflight.data.readyForLocalBuild ? "ready" : "blocked"}</div>{preflight.data.targets.map((target) => <div key={target.id} className="rounded-xl bg-zinc-50 p-3 text-xs dark:bg-zinc-950"><strong>{target.label}</strong><p className="mt-1 text-[10px] text-zinc-500">{target.platforms.join(" / ")} · source {target.matrix.source} · local build {target.matrix.localBuild}</p></div>)}{preflight.data.diagnostics.map((item, index) => <div key={`${item.code}-${index}`} className={`rounded-lg p-2 text-[10px] ${item.severity === "error" ? "bg-red-50 text-red-700 dark:bg-red-950/30 dark:text-red-300" : "bg-amber-50 text-amber-700 dark:bg-amber-950/30"}`}><strong>{item.code}</strong> · {item.message}<code className="mt-1 block break-all opacity-70">{item.path}</code></div>)}</section>}
    {capabilities && <p className="mt-3 text-[10px] leading-relaxed text-zinc-400">Host: {capabilities.host.os} / {capabilities.host.architecture} · SDK {Object.entries(capabilities.host.sdks).filter(([, available]) => available).map(([name]) => name).join(", ") || "none"}</p>}
  </section>;
}
