"""baseline current schema

Revision ID: dd6115224a90
Revises:
Create Date: 2026-07-20 19:54:37.474928
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'dd6115224a90'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('electricity_daily',
    sa.Column('local_date', sa.String(length=10), nullable=False),
    sa.Column('energy_kwh', sa.Float(), nullable=False),
    sa.Column('cost_yen', sa.Float(), nullable=False),
    sa.Column('price_per_kwh_yen', sa.Float(), nullable=False),
    sa.Column('sample_duration_sec', sa.Float(), nullable=False),
    sa.Column('first_sample_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sample_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('local_date')
    )
    op.create_table('electricity_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boot_id', sa.String(length=64), nullable=False),
    sa.Column('session_energy_kwh', sa.Float(), nullable=False),
    sa.Column('session_cost_yen', sa.Float(), nullable=False),
    sa.Column('last_input_power_w', sa.Float(), nullable=True),
    sa.Column('last_sample_wall_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_persisted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('git_repositories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('managed_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('application_type', sa.String(length=32), nullable=False),
    sa.Column('icon_path', sa.String(length=512), nullable=True),
    sa.Column('working_directory', sa.String(length=1024), nullable=True),
    sa.Column('executable_path', sa.String(length=1024), nullable=True),
    sa.Column('script_path', sa.String(length=1024), nullable=True),
    sa.Column('python_path', sa.String(length=1024), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=True),
    sa.Column('web_port', sa.Integer(), nullable=True),
    sa.Column('arguments_json', sa.Text(), nullable=False),
    sa.Column('environment_json_encrypted', sa.Text(), nullable=True),
    sa.Column('run_as_user', sa.String(length=64), nullable=True),
    sa.Column('auto_start', sa.Boolean(), nullable=False),
    sa.Column('restart_policy', sa.String(length=32), nullable=False),
    sa.Column('stop_timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('health_check_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('systemd_unit_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metrics_minute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cpu_percent', sa.Float(), nullable=True),
    sa.Column('memory_percent', sa.Float(), nullable=True),
    sa.Column('gpu_percent', sa.Float(), nullable=True),
    sa.Column('vram_percent', sa.Float(), nullable=True),
    sa.Column('disk_read_bps', sa.Float(), nullable=True),
    sa.Column('disk_write_bps', sa.Float(), nullable=True),
    sa.Column('net_rx_bps', sa.Float(), nullable=True),
    sa.Column('net_tx_bps', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('metrics_minute', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_minute_timestamp'), ['timestamp'], unique=False)

    op.create_table('notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('channel_type', sa.String(length=16), nullable=False),
    sa.Column('url_encrypted', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('remote_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('protocol', sa.String(length=8), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('secret_params_encrypted', sa.Text(), nullable=True),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('is_self', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('permissions_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workflow_secrets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('alert_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('operator', sa.String(length=4), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('app_id', sa.Integer(), nullable=True),
    sa.Column('channel_ids_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['managed_applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('recovery_codes_encrypted', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('alert_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notified', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['alert_rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alert_events_rule_id'), ['rule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alert_events_triggered_at'), ['triggered_at'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=32), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('progress_json', sa.Text(), nullable=False),
    sa.Column('events_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)

    op.create_table('project_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=128), nullable=False),
    sa.Column('project_name', sa.String(length=128), nullable=False),
    sa.Column('profile_id', sa.String(length=64), nullable=False),
    sa.Column('profile_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('unit_name', sa.String(length=128), nullable=False),
    sa.Column('command_json', sa.Text(), nullable=False),
    sa.Column('environment_names_json', sa.Text(), nullable=False),
    sa.Column('working_directory', sa.String(length=1024), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('web_port', sa.Integer(), nullable=True),
    sa.Column('initial_artifacts_json', sa.Text(), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_redacted', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_name')
    )
    with op.batch_alter_table('project_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_runs_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_runs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_runs_web_port'), ['web_port'], unique=False)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_session_token_hash'), ['session_token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('terminal_automation_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('snippet_ids_json', sa.Text(), nullable=False),
    sa.Column('parameters_encrypted', sa.Text(), nullable=True),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('target_session_id', sa.String(length=8), nullable=True),
    sa.Column('working_directory', sa.String(length=1024), nullable=False),
    sa.Column('condition_type', sa.String(length=24), nullable=False),
    sa.Column('condition_value', sa.String(length=128), nullable=False),
    sa.Column('recurrence', sa.String(length=16), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('run_if_missed', sa.Boolean(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_result', sa.String(length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_username', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terminal_automation_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terminal_automation_schedules_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminal_automation_schedules_enabled'), ['enabled'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminal_automation_schedules_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminal_automation_schedules_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminal_automation_schedules_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminal_automation_schedules_target_session_id'), ['target_session_id'], unique=False)

    op.create_table('terminal_snippets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('description', sa.String(length=320), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('variables_json', sa.Text(), nullable=False),
    sa.Column('tags_json', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('terminal_snippets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terminal_snippets_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminal_snippets_name'), ['name'], unique=True)

    op.create_table('workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('definition_json', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('application_spec_json', sa.Text(), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=32), nullable=False),
    sa.Column('application_type', sa.String(length=32), nullable=False),
    sa.Column('ui_framework', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_projects_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_projects_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('chat_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('thinking', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('meta_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_messages_conversation_id'), ['conversation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_messages_created_at'), ['created_at'], unique=False)

    op.create_table('chat_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=32), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('short_id', sa.String(length=12), nullable=False),
    sa.Column('canonical_key', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('provider', sa.String(length=128), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conversation_id', 'canonical_key', name='uq_chat_reference_canonical'),
    sa.UniqueConstraint('conversation_id', 'sequence', name='uq_chat_reference_sequence'),
    sa.UniqueConstraint('conversation_id', 'short_id', name='uq_chat_reference_short_id')
    )
    with op.batch_alter_table('chat_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_references_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('job_controls',
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('owner_user_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('job_id'),
    sa.UniqueConstraint('owner_user_id', 'kind', 'idempotency_key', name='uq_job_control_idempotency')
    )
    with op.batch_alter_table('job_controls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_controls_heartbeat_at'), ['heartbeat_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_controls_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_controls_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table('project_run_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('mime_type', sa.String(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('change_type', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['project_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_run_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_run_artifacts_run_id'), ['run_id'], unique=False)

    op.create_table('terminal_command_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('snippet_ids_json', sa.Text(), nullable=False),
    sa.Column('command_snapshot_encrypted', sa.Text(), nullable=False),
    sa.Column('command_checksum', sa.String(length=64), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('target_session_id', sa.String(length=8), nullable=True),
    sa.Column('working_directory', sa.String(length=1024), nullable=False),
    sa.Column('condition_type', sa.String(length=24), nullable=False),
    sa.Column('condition_value', sa.String(length=128), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('unit_name', sa.String(length=128), nullable=True),
    sa.Column('output_path', sa.String(length=1024), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_by_username', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['terminal_automation_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_name')
    )
    with op.batch_alter_table('terminal_command_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_terminal_command_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminal_command_runs_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminal_command_runs_schedule_id'), ['schedule_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminal_command_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_terminal_command_runs_target_session_id'), ['target_session_id'], unique=False)

    op.create_table('workflow_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('definition_json', sa.Text(), nullable=False),
    sa.Column('input_schema_json', sa.Text(), nullable=False),
    sa.Column('output_schema_json', sa.Text(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_versions_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('application_builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('framework', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('unit_name', sa.String(length=128), nullable=False),
    sa.Column('build_root', sa.String(length=1024), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.Column('archive_checksum', sa.String(length=64), nullable=False),
    sa.Column('generator_json', sa.Text(), nullable=False),
    sa.Column('sdk_name', sa.String(length=32), nullable=False),
    sa.Column('sdk_path', sa.String(length=1024), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=64), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_redacted', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['application_projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unit_name')
    )
    with op.batch_alter_table('application_builds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_builds_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_builds_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_application_builds_status'), ['status'], unique=False)

    op.create_table('workflow_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('context_json', sa.Text(), nullable=False),
    sa.Column('workflow_version_id', sa.Integer(), nullable=True),
    sa.Column('definition_snapshot_json', sa.Text(), nullable=False),
    sa.Column('runtime_snapshot_json', sa.Text(), nullable=False),
    sa.Column('last_event_sequence', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.ForeignKeyConstraint(['workflow_version_id'], ['workflow_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_executions_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('application_build_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=2048), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('mime_type', sa.String(length=256), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['build_id'], ['application_builds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_build_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_build_artifacts_build_id'), ['build_id'], unique=False)

    op.create_table('workflow_execution_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'sequence', name='uq_workflow_execution_event_sequence')
    )
    with op.batch_alter_table('workflow_execution_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_execution_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_execution_events_execution_id'), ['execution_id'], unique=False)

    op.create_table('workflow_node_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('node_type', sa.String(length=64), nullable=False),
    sa.Column('node_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('resolved_inputs_json', sa.Text(), nullable=False),
    sa.Column('outputs_json', sa.Text(), nullable=False),
    sa.Column('error_json', sa.Text(), nullable=False),
    sa.Column('logs_json', sa.Text(), nullable=False),
    sa.Column('artifacts_json', sa.Text(), nullable=False),
    sa.Column('token_usage_json', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('elapsed_ms', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('cache_source', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_node_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_node_runs_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_node_runs_node_id'), ['node_id'], unique=False)

    op.create_table('workflow_pinned_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('output_json', sa.Text(), nullable=False),
    sa.Column('source_execution_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_execution_id'], ['workflow_executions.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'node_id', name='uq_workflow_pinned_node')
    )
    with op.batch_alter_table('workflow_pinned_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_pinned_data_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_test_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('inputs_json', sa.Text(), nullable=False),
    sa.Column('mocks_json', sa.Text(), nullable=False),
    sa.Column('expected_outputs_json', sa.Text(), nullable=False),
    sa.Column('assertions_json', sa.Text(), nullable=False),
    sa.Column('last_execution_id', sa.Integer(), nullable=True),
    sa.Column('last_status', sa.String(length=16), nullable=False),
    sa.Column('last_result_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_execution_id'], ['workflow_executions.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_test_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_test_cases_workflow_id'), ['workflow_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_test_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_test_cases_workflow_id'))

    op.drop_table('workflow_test_cases')
    with op.batch_alter_table('workflow_pinned_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_pinned_data_workflow_id'))

    op.drop_table('workflow_pinned_data')
    with op.batch_alter_table('workflow_node_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_node_runs_node_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_node_runs_execution_id'))

    op.drop_table('workflow_node_runs')
    with op.batch_alter_table('workflow_execution_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_execution_events_execution_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_execution_events_created_at'))

    op.drop_table('workflow_execution_events')
    with op.batch_alter_table('application_build_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_build_artifacts_build_id'))

    op.drop_table('application_build_artifacts')
    with op.batch_alter_table('workflow_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_executions_workflow_id'))

    op.drop_table('workflow_executions')
    with op.batch_alter_table('application_builds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_builds_status'))
        batch_op.drop_index(batch_op.f('ix_application_builds_project_id'))
        batch_op.drop_index(batch_op.f('ix_application_builds_created_by'))

    op.drop_table('application_builds')
    with op.batch_alter_table('workflow_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_versions_workflow_id'))

    op.drop_table('workflow_versions')
    with op.batch_alter_table('terminal_command_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminal_command_runs_target_session_id'))
        batch_op.drop_index(batch_op.f('ix_terminal_command_runs_status'))
        batch_op.drop_index(batch_op.f('ix_terminal_command_runs_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_terminal_command_runs_created_by'))
        batch_op.drop_index(batch_op.f('ix_terminal_command_runs_created_at'))

    op.drop_table('terminal_command_runs')
    with op.batch_alter_table('project_run_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_run_artifacts_run_id'))

    op.drop_table('project_run_artifacts')
    with op.batch_alter_table('job_controls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_controls_owner_user_id'))
        batch_op.drop_index(batch_op.f('ix_job_controls_kind'))
        batch_op.drop_index(batch_op.f('ix_job_controls_heartbeat_at'))

    op.drop_table('job_controls')
    with op.batch_alter_table('chat_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_references_conversation_id'))

    op.drop_table('chat_references')
    with op.batch_alter_table('chat_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_messages_created_at'))
        batch_op.drop_index(batch_op.f('ix_chat_messages_conversation_id'))

    op.drop_table('chat_messages')
    with op.batch_alter_table('application_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_projects_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_application_projects_name'))

    op.drop_table('application_projects')
    op.drop_table('workflows')
    with op.batch_alter_table('terminal_snippets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminal_snippets_name'))
        batch_op.drop_index(batch_op.f('ix_terminal_snippets_created_by'))

    op.drop_table('terminal_snippets')
    with op.batch_alter_table('terminal_automation_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_terminal_automation_schedules_target_session_id'))
        batch_op.drop_index(batch_op.f('ix_terminal_automation_schedules_status'))
        batch_op.drop_index(batch_op.f('ix_terminal_automation_schedules_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_terminal_automation_schedules_name'))
        batch_op.drop_index(batch_op.f('ix_terminal_automation_schedules_enabled'))
        batch_op.drop_index(batch_op.f('ix_terminal_automation_schedules_created_by'))

    op.drop_table('terminal_automation_schedules')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_session_token_hash'))

    op.drop_table('sessions')
    with op.batch_alter_table('project_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_runs_web_port'))
        batch_op.drop_index(batch_op.f('ix_project_runs_status'))
        batch_op.drop_index(batch_op.f('ix_project_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_runs_created_by'))

    op.drop_table('project_runs')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_kind'))
        batch_op.drop_index(batch_op.f('ix_jobs_created_at'))

    op.drop_table('jobs')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_owner_user_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('alert_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alert_events_triggered_at'))
        batch_op.drop_index(batch_op.f('ix_alert_events_rule_id'))

    op.drop_table('alert_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('alert_rules')
    op.drop_table('workflow_secrets')
    op.drop_table('roles')
    op.drop_table('remote_connections')
    op.drop_table('notification_channels')
    with op.batch_alter_table('metrics_minute', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_minute_timestamp'))

    op.drop_table('metrics_minute')
    op.drop_table('managed_applications')
    op.drop_table('git_repositories')
    op.drop_table('electricity_state')
    op.drop_table('electricity_daily')
    # ### end Alembic commands ###
