"""workflow pauses and artifacts

Revision ID: e2689f3f0c28
Revises: dd6115224a90
Create Date: 2026-07-20 20:28:16.656015
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e2689f3f0c28'
down_revision: Union[str, Sequence[str], None] = 'dd6115224a90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_pauses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('pause_type', sa.String(length=24), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('approver', sa.String(length=64), nullable=False),
    sa.Column('form_schema_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_pauses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_pauses_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_pauses_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_pauses_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_pauses_status'), ['status'], unique=False)

    op.create_table('workflow_artifacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sa.Integer(), nullable=False),
    sa.Column('node_run_id', sa.Integer(), nullable=True),
    sa.Column('node_id', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=160), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ),
    sa.ForeignKeyConstraint(['node_run_id'], ['workflow_node_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('workflow_artifacts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_artifacts_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_artifacts_node_id'), ['node_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_artifacts_node_run_id'), ['node_run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_artifacts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_artifacts_node_run_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_artifacts_node_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_artifacts_execution_id'))

    op.drop_table('workflow_artifacts')
    with op.batch_alter_table('workflow_pauses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_pauses_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_pauses_node_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_pauses_expires_at'))
        batch_op.drop_index(batch_op.f('ix_workflow_pauses_execution_id'))

    op.drop_table('workflow_pauses')
    # ### end Alembic commands ###
